services:
  sonarr:  # Points to series
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}/content/series:/tv
      - ${MEDIA_DIR}/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:  # Points to movies
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}/content/movies:/movies
      - ${MEDIA_DIR}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:  # Indexer
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:  # Solves captchas
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - "8191:8191"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}/content/series:/tv
      - ${MEDIA_DIR}/content/movies:/movies
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8080:8080     # qBittorrent web UI
      - 6881:6881     # Torrenting TCP
      - 6881:6881/udp # Torrenting UDP
    volumes:
      - ${CONFIG_DIR}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=pia
      - VPN_TYPE=wireguard
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - SERVER_REGIONS=${PIA_REGION}
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=pia
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24,100.64.0.0/10
      - DOT_PROVIDERS=cloudflare,google
      - TZ=${TZ}
      - LOG_LEVEL=info

  gluetun-qbittorrent-port-manager:
    image: patrickaclark/gluetun-qbittorrent-port-manager:latest
    container_name: qb-port-manager
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - QBITTORRENT_SERVER=localhost
      - QBITTORRENT_PORT=8080
      - PORT_FORWARDED=/gluetun/forwarded_port
      - HTTP_S=http
      - GLUETUN_HOST=localhost
      - GLUETUN_PORT=8000
      - RECHECK_TIME=60
      - TZ=${TZ}

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${MEDIA_DIR}/downloads:/downloads
    restart: unless-stopped

